name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.08"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb3ed60367a8ecfa8dd8e5d26cd84372e946eb41ec6d78c95c9115f50a8d0443"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
