name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.19"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fae10cee4108441c0f3f2f1bcfc05d55bec53554c21aefd2130c362f4b1f440"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
