name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.07"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84bd088d5e513a51c350fbf21d73a75a8b49def78c4863d7e128fc5e09e97825"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
