name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ef318ae0626692090eff97a936a6575948a2e18bdb5da5b4a08f8fe6a24eb63"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
