name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.15"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7496958aa40c1e980bc27d2588c9a94c53a3c6acc0bf00acf3a79b6f12db5208"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
