name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00a2b1e0536054e283c831bf65a61f7aa02c56b7752de02f770f4dc7b46dfd87"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
