name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.08"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeb1d2b9b9a708d7d49318749c318478352bc26d1f4bb7eea0f334895f3986ac"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
