name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.11"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "152dadc296f06d674550c3da9ea825257ec00f7c8ed7dda19359bfa84b4f25c7"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
