name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.18"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1a1953db9992a3f6a0bd653fe756f8b9e29005a26b4b0369f801e4e220fe2de"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
