name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.11"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0edd24f40b3a948fc56b60c860fcf1a3c3b6cced05de47578c64e8151339a175"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
