name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.17"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3532fdb283807038579710a9e18c9ef5418d781ba210fdb98f49b9ee5b2b7d5f"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
