name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.19"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0452bdeba29212a040fdcf0c9e25412b66868916e3614bfaf64c11ac7e8439ce"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
