name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.15"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cede7c29ee779496da14ef49afc0558580a6e1796e52bd6b227adca371cee05"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
