name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a30b5fff2980ad6de70a88536f15cfe770d88a6a46f5f5b12c5fb253d5c473c"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
