name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.18"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58e0c3cc4d9566d0e259328b750fb4cbcca79c36854ba99f40221aa183076cc1"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
