name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.26"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e9e7d3eae1e27ebbf9ef3964cf128a25d8f413745aa13277d87f73153894d01"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
