name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.09"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b5aa1e0f1283c1feb33032a276bf8d1a603e6d919be3ec7d506ce5bf669c781"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
