name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.27"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc33305ce795c07fe85217c9cbf46d62200678ada300d5bb07d94608f0427da2"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
