name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.09"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91f69a840d461fe2dd97c85b382d29c10c52afff8c59ff5eba286fa53f4fce93"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
