name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.19"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb66c66ec6ae0d77b95367829011b3c6f2e733d5a5c9a19c2729dba887e28d28"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
