name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.13"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7c0a474a864019c9ca4fa10ce5e28afbcf58e645e85638984cc6600927c58f2"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
