name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.27"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdd20371730c0a36f86ec3ec76706fd87b9319341f043183c3bb77624abe5be8"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
