name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.08"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbe6f3bb95638a455ef6e4dda3f03e9851f9d09ab42d3464bd3a1a241694608e"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
