name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.11"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b856576c1db15b191a0c61a6bd6626c7ea73392d68abe8ee48e3089fb8e6f277"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
