name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.13"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9aa9d2253d1cd779bdd673f41474097d63e83b44deb9048e0dc93931f1318cc"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
