name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.08"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9396e9ad6221c99be5a977c25a8000e418d6aeb6b6e882f331d1ab8533c0aed5"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.16"
