name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.11"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02e36731d3ccbfeb6e64543dbad0855ffa61a2b39119bd6fb2fd253901b94ce5"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
