name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.13"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "430e3f29f2e07c3fcc104a03834028b759e43dfa2ca1d1cd239de77151a6eaf4"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
