name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.04"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d896f1a8f5dca49567371c43b75ab12973174d5fbc41e86a56351464ba06fd64"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
