name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbdcce9849729e2939f89231a98adefae9f0be435c0138b9e7a8430377242794"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
