name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.10"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60c39976d34c394297b453fc74c825b478a09bc8f0af1534c0de3f6e86b9fe33"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
