name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.08"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5e9a449d891fbd42ab8935bdb1a72e8ce7f0fe85dbb19aa9ff9ca98cadbbca9"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
