name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.16"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bacdaddb998b7da5ca09ab41beceef470f78c9ce105d34aae627638b8682e94d"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
