name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.04"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a28909bf5b8c4d034a77375b04a393d2436945cda86efaf0798970edbfafb40"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
