name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.01"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cc73f11c599424942ab3b00ab2eb54dd0f1e00ff791003c215b2af1a43c20df"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
