name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.15"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5eda1263e1f993f95d9970e7f5fd05e92c3c2b5d3f085465ea81296c136692ab"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
