name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.19"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f92b9fdc46a8cf2b4362a9f27fac61be822ce187f8a9ce4382658361c040707"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
