name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2181376b40ef450db9e502d70e35aa3a87cb9876ee8c30768e995f0aea2a0564"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
