name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.14"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0bf13f37b3dba484442c85dd86b04fed6417821d0372cf1e6e31ecfc7607ba9"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
