name = "BlanketCon 2022"
author = "The community!"
version = "2022.06.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a7d2b5eac37421bef17d39c176603b60fa3fe1177a5c45090f71b9c81323d42"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0"
