name = "Architecture Extensions"
filename = "architecture_extensions-0.2.0-pre4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/YyhsabMU/versions/v0.2.0-pre4/architecture_extensions-0.2.0-pre4.jar"
hash-format = "sha1"
hash = "89cd9a35610fdd32ec47d841b59aae17d5857b28"

[update]
[update.modrinth]
mod-id = "YyhsabMU"
version = "l6j74ZUA"
