name = "Bewitchment"
filename = "bewitchment-1.18-20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3790/211/bewitchment-1.18-20.jar"
hash-format = "sha1"
hash = "94e81d8a5b17d4738f6236634fd24c3fb3a1f0b9"

[update]
[update.curseforge]
file-id = 3790211
project-id = 394915
