name = "BlanketCon Patches"
filename = "blanketconpatches-0.0.1.jar"
side = "both"

[download]
url = "https://github.com/parzivail/blanketcon-patches/releases/download/0.0.1/blanketconpatches-0.0.1.jar"
hash-format = "sha1"
hash = "b6851faed7a74ae40e422b13301758fe0c722658"
