name = "Botania (Fabric)"
filename = "Botania-1.18.2-432-FABRIC.jar"
side = "both"

[download]
url = "https://ci.blamejared.com/job/Violet%20Moon/job/Botania/view/tags/job/release-1.18.2-432/lastSuccessfulBuild/artifact/Fabric/build/libs/Botania-1.18.2-432-FABRIC.jar"
hash-format = "sha1"
hash = "e486d749d9faff7a8f0221f1ade3c287dbfcb976"
