name = "Botania (Fabric)"
filename = "Botania-1.18.2-432-FABRIC.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3789/681/Botania-1.18.2-432-FABRIC.jar"
hash-format = "sha1"
hash = "e486d749d9faff7a8f0221f1ade3c287dbfcb976"

[update]
[update.curseforge]
file-id = 3789681
project-id = 421839
