name = "cardstock"
filename = "cardstock-1.1.0.jar"
side = "both"

[download]
url = "https://github.com/repulica/CardStock/releases/download/1.1.0/cardstock-1.1.0.jar"
hash-format = "sha1"
hash = "3a394072ab4a3aa1586ec685c3bc562056260f85"
