name = "CC: Restitched"
filename = "cc-restitched-1.100.6.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/968781492899704862/972789806415368192/cc-restitched-1.100.6.jar"
hash-format = "sha1"
hash = "2fa8a582d7fef34fbf1ed4e2cc8cb25b9c35ccb5"
