name = "Create Fabric"
filename = "create-mc1.18.2_v0.4.1+576.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Xbc0uyRg/versions/mc1.18.2_v0.4.1+576/create-mc1.18.2_v0.4.1%2B576.jar"
hash-format = "sha1"
hash = "68c11b3683b7ebeb8044e1a4f794b3ee5dc1d949"

[update]
[update.modrinth]
mod-id = "Xbc0uyRg"
version = "ce9nGr3a"
