name = "Create Refabricated"
filename = "Create-mc1.18.2_v0.4.1+553.jar"
side = "both"

[download]
url = "https://mvn.devos.one/snapshots/com/simibubi/Create/mc1.18.2_v0.4.1+553/Create-mc1.18.2_v0.4.1+553.jar"
hash-format = "sha1"
hash = "5b16cf6d5fe8601564e84b58da8b1614ca0dba23"
