name = "Enchancement"
filename = "enchancement-1.18-12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3785/423/enchancement-1.18-12.jar"
hash-format = "sha1"
hash = "9819dd18b9b7500345ba1a8618d333f7e7350bef"

[update]
[update.curseforge]
file-id = 3785423
project-id = 598056
