name = "Enchancement"
filename = "enchancement-1.18-15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3788/303/enchancement-1.18-15.jar"
hash-format = "sha1"
hash = "96afee4abe36fdc27c7cffb2b310ecae8ded123e"

[update]
[update.curseforge]
file-id = 3788303
project-id = 598056
