name = "GeckoLib"
filename = "geckolib-fabric-1.18-3.0.41.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3785/778/geckolib-fabric-1.18-3.0.41.jar"
hash-format = "sha1"
hash = "30d320286075c84b8a9dae346b3bb20538700f73"

[update]
[update.curseforge]
file-id = 3785778
project-id = 388172
