name = "Haema"
filename = "haema-1.9.7+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3786/161/haema-1.9.7+1.18.2.jar"
hash-format = "sha1"
hash = "757bec8343840130c93635557b6c07b3b9c4624a"

[update]
[update.curseforge]
file-id = 3786161
project-id = 391257
