name = "Halfdoors"
filename = "half-doors-1.18.2-fabric-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3790/274/half-doors-1.18.2-fabric-1.2.0.jar"
hash-format = "sha1"
hash = "f59eacb220492b33af0b7c170f432d79229e8d31"

[update]
[update.curseforge]
file-id = 3790274
project-id = 596375
