name = "Jamtastic"
filename = "jamtastic-1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3791/352/jamtastic-1.4.1.jar"
hash-format = "sha1"
hash = "00edb8d4627f0c660323c0221049ee1a6a18ddf4"

[update]
[update.curseforge]
file-id = 3791352
project-id = 559060
