name = "Plasmid"
filename = "plasmid-0.5+1.18.2-SNAPSHOT.jar"
side = "server"

[download]
url = "https://cdn.discordapp.com/attachments/968781492899704862/975483083585355846/plasmid-0.51.18.2-SNAPSHOT.jar"
hash-format = "sha1"
hash = "77f4c49a70c3811eac1d4bffae1aa804ee6aad71"
