name = "Polaroid Camera "
filename = "polaroidcamera-1.2.5.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9dPDuh0K/versions/v1.2.5/polaroidcamera-1.2.5.jar"
hash-format = "sha1"
hash = "fa3825e2012bfa2c3b3c458c3dcaa6dfbf1edc19"

[update]
[update.modrinth]
mod-id = "9dPDuh0K"
version = "TPz1kC23"
