name = "Polaroid Camera "
filename = "polaroidcamera-1.2.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9dPDuh0K/versions/1.2.4/polaroidcamera-1.2.4.jar"
hash-format = "sha1"
hash = "1152fae21ab20862f2f719fd9714b4b9cd6eaec0"

[update]
[update.modrinth]
mod-id = "9dPDuh0K"
version = "3tpZmOx0"
