name = "Portal Cubed"
filename = "portal_cubed-2.1.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GUwDZ4ZU/versions/1.18.2+fabric/portal_cubed-2.1.1.jar"
hash-format = "sha1"
hash = "c0e6125826d9785c6bf60d7d0514884741cccb47"

[update]
[update.modrinth]
mod-id = "GUwDZ4ZU"
version = "vXIIMKFq"
