name = "Portal Cubed"
filename = "portal_cubed-2.1.6.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GUwDZ4ZU/versions/2.1.6+fabric/portal_cubed-2.1.6.jar"
hash-format = "sha1"
hash = "b2188bfa3e7f5067788dcbea09d930c81348e930"

[update]
[update.modrinth]
mod-id = "GUwDZ4ZU"
version = "JRJYtZYg"
