name = "Portal Cubed"
filename = "portal_cubed-2.0.8.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/968781492899704862/973961856903442513/portal_cubed-2.0.8.jar"
hash-format = "sha1"
hash = "edfada5dcee8c54a2a809fd32b32f76bfd1a159d"
