name = "Galaxies: Parzi's Star Wars Mod"
filename = "pswg-0.0.68+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3783/639/pswg-0.0.68+1.18.2.jar"
hash-format = "sha1"
hash = "6138246e5d91077094142488158787b920ba1043"

[update]
[update.curseforge]
file-id = 3783639
project-id = 496522
