name = "Purpeille"
filename = "purpeille-2.0.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/yoEkK5RL/versions/2.0.0/purpeille-2.0.0.jar"
hash-format = "sha1"
hash = "3094a391bdea9d088ce1f3f4577d0cc5cf109389"

[update]
[update.modrinth]
mod-id = "yoEkK5RL"
version = "G3EEEyW2"
