name = "Purpeille"
filename = "purpeille-2.1.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/yoEkK5RL/versions/2.1.1/purpeille-2.1.1.jar"
hash-format = "sha1"
hash = "a6fe35aec017f0d802e0a098b0750a932766123c"

[update]
[update.modrinth]
mod-id = "yoEkK5RL"
version = "w9ZuPuMW"
