name = "Purpeille"
filename = "purpeille-2.2.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/yoEkK5RL/versions/2.2.0/purpeille-2.2.0.jar"
hash-format = "sha1"
hash = "58282ce4e3fc59792a309624f75f11f7c2a19f2a"

[update]
[update.modrinth]
mod-id = "yoEkK5RL"
version = "96xrBTr9"
