name = "Refined Magic"
filename = "refmagic-1.0.0-betat5.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/yTtdp6Mq/versions/1.0.0-beta5/refmagic-1.0.0-betat5.jar"
hash-format = "sha1"
hash = "7f2c0fa64e62bd8b82c1455ed2ccc4209fcb2975"

[update]
[update.modrinth]
mod-id = "yTtdp6Mq"
version = "a5txNSG2"
