name = "Refined Magic"
filename = "refmagic-1.0.0-beta9.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/968781492899704862/976462669282439188/refmagic-1.0.0-beta9.jar"
hash-format = "sha1"
hash = "b7d26bba9cdf67fa2ec78dca903f7f43f3c864e5"
