name = "Refined Magic"
filename = "refmagic-1.0.0-beta9.4.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/968781492899704862/976950150599692319/refmagic-1.0.0-beta9.4.jar"
hash-format = "sha1"
hash = "a2346848feda2f58c77bd6fbbf2b9ad3ffad4a5e"
