name = "TerrariaMod"
filename = "terrariamod-1.0.0.jar"
side = "both"

[download]
url = "https://github.com/Ryorama/Terrariamod/releases/download/1.0.4/terrariamod-1.0.0.jar"
hash-format = "sha1"
hash = "c6effde34013a17c26c32b17b61873baffae2bf8"
