name = "TerrariaMod"
filename = "terrariamod-1.0.0.jar"
side = "both"

[download]
url = "https://github.com/Ryorama/Terrariamod/releases/download/1.0.1/terrariamod-1.0.0.jar"
hash-format = "sha1"
hash = "1a330e9e25ca346811703d0219b8db92aad68bae"
