name = "Soul Ice"
filename = "soulice-1.3.0+1.18.2-quilt.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ngBlYV53/versions/1.3.0+Quilt-1.18.2/soulice-1.3.0%2B1.18.2-quilt.jar"
hash-format = "sha1"
hash = "501d70740d6eddbecd5c943ad69b8be443babf16"

[update]
[update.modrinth]
mod-id = "ngBlYV53"
version = "YdfocEdb"
