name = "Wired Redstone"
filename = "wired-redstone-0.2.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/lyYGrdho/versions/0.2.4/wired-redstone-0.2.4.jar"
hash-format = "sha1"
hash = "3623f699faccb21c9d414bf050c302ee67c36d41"

[update]
[update.modrinth]
mod-id = "lyYGrdho"
version = "MOllEHTn"
